trigger: none
pr: none

stages:
- stage: BuildAndDeploy
  displayName: 'Build and Deploy to Test'
  jobs:
  - job: Build
    displayName: 'Build Project'
    pool:
      vmImage: 'windows-latest'
    steps:
    - checkout: self
    - task: UseDotNet@2
      inputs:
        version: '8.0.x'
    - script: |
        cd ThePizzaDatabaseAPI
        dotnet build --configuration Release --output $(Build.ArtifactStagingDirectory)/output
      displayName: 'Build project'
    - publish: $(Build.ArtifactStagingDirectory)/output
      artifact: drop

  - deployment: Deploy
    displayName: 'Deploy to Test'
    environment: 'Test'
    dependsOn: Build
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureFunctionApp@2
            inputs:
              azureSubscription: 'serviceConnectionPizzaDatabaseApi'
              appType: 'functionApp'
              appName: 'func-the-pizza-database-api'
              package: '$(Pipeline.Workspace)/drop'