trigger: none

stages:
- stage: Deploy
  displayName: 'Deploy to Test Function App'
  jobs:
  - deployment: DeployJob
    displayName: 'Deploy ThePizzaDatabaseAPI'
    environment: 'Test' 
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: UseDotNet@2
            inputs:
              version: '8.0.x'

          - script: |
              cd ThePizzaDatabaseAPI
              dotnet build --configuration Release --output $(Build.ArtifactStagingDirectory)/output
            displayName: 'Build project'

          - task: AzureFunctionApp@2
            inputs:
              azureSubscription: 'serviceConnectionPizzaDatabaseApi'
              appType: 'functionApp'
              appName: 'func-the-pizza-database-api'
              package: '$(Build.ArtifactStagingDirectory)/output'